name: UID
# Updates the UID regex from the cylc-flow source code

on:
  workflow_dispatch:
  schedule:
    - cron: '25 4 1 1 *' # Every Jan 1st @ 04:25 UTC

jobs:
  uid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cylc-ui
        uses: actions/checkout@v2

      - name: Checkout cylc-flow
        uses: actions/checkout@v2
        with:
          repository: 'cylc/cylc-flow'
          ref: 'master'
          path: 'cylc-flow'

      - name: Configure Python
        uses: actions/setup-python@v3.1.1
        with:
          python-version: 3.9

      - name: Install
        run:
          pip install ./cylc-flow

      - name: Configure git
        uses: cylc/release-actions/configure-git@v1

      - name: Checkout PR branch
        uses: cylc/release-actions/checkout-copyright-branch@v1

      - name: Check diff
        id: diff
        run: |
          echo 'foo' >> README.md
          # python etc/uid.py --fix
          if $(git diff); then
            echo '::set-output name=changed::false'
          else
            echo '::set-output name=changed::true'
            git add -u
            git commit -m 'uid: update regex'
          fi

      - name: Create pull request
        if: steps.diff.outputs.output_changed
        uses: cylc/release-actions/create-pr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: ${{ env.BRANCH_NAME }}
          title: 'Auto PR: update UID pattern'
          body: 'Update UID regex to match cylc-flow.'
